---
- hosts: all
  gather_facts: true
  become: true
  tasks: 
  - name: Create a simple file
    file: 
      path: /opt/ansible.txt
      state: touch 
      
  - name: Task name
    stat:
      path: /opt/
    register: register_name
